-- 주의: 실제 운영에 쓰지 마세요. PART 4 시연용입니다.
-- "화면에서 PIN 번호만 확인하고, DB는 누구나 고칠 수 있게 열어 둔" 가게를 일부러 만듭니다.
create table if not exists public.acm_pin_demo (
  id bigint generated by default as identity primary key,
  name text not null,
  price int not null
);
revoke all on public.acm_pin_demo from anon, authenticated;
grant select, update on public.acm_pin_demo to anon;
alter table public.acm_pin_demo enable row level security;
drop policy if exists "PIN 화면만 믿고 누구나 수정" on public.acm_pin_demo;
create policy "PIN 화면만 믿고 누구나 수정" on public.acm_pin_demo
  for all to anon using (true) with check (true);
insert into public.acm_pin_demo (name, price)
select '오후세시 라떼', 6000 where not exists (select 1 from public.acm_pin_demo);

-- 시연이 끝나면 아래 한 줄을 따로 실행해 지우세요.
-- drop table public.acm_pin_demo;
