-- 오후세시 커피 메뉴판: 표, 권한, 보안 규칙(RLS), 샘플 메뉴를 한 번에 만듭니다.
-- Supabase 대시보드의 SQL Editor에 전부 붙여넣고 실행하세요.
-- 여러 번 실행해도 괜찮습니다. 이미 있는 표와 메뉴는 그대로 둡니다.

create table if not exists public.acm_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  name_en text,
  sort int not null default 0
);

create table if not exists public.acm_menu_items (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.acm_categories(id) on delete cascade,
  name text not null,
  name_en text,
  price int not null check (price >= 0),
  description text,
  image text,
  sold_out boolean not null default false,
  sort int not null default 0,
  visible boolean not null default true
);

create table if not exists public.acm_owners (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- 1) 권한: 손님(anon)은 읽기만. 로그인한 사람(authenticated)은 쓰기를 "시도"할 수 있고,
--    실제로 누가 쓸 수 있는지는 아래 2) 보안 규칙이 정합니다.
revoke all on public.acm_categories, public.acm_menu_items, public.acm_owners from anon, authenticated;
grant select on public.acm_categories, public.acm_menu_items to anon, authenticated;
grant insert, update, delete on public.acm_categories, public.acm_menu_items to authenticated;
grant select on public.acm_owners to authenticated;

-- 2) 보안 규칙(RLS): 켜는 순간, 규칙에 맞는 줄만 통과합니다.
alter table public.acm_categories enable row level security;
alter table public.acm_menu_items enable row level security;
alter table public.acm_owners enable row level security;

drop policy if exists "누구나 종류 보기" on public.acm_categories;
create policy "누구나 종류 보기" on public.acm_categories
  for select to anon, authenticated using (true);
drop policy if exists "사장님만 종류 추가" on public.acm_categories;
create policy "사장님만 종류 추가" on public.acm_categories
  for insert to authenticated
  with check (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())));
drop policy if exists "사장님만 종류 수정" on public.acm_categories;
create policy "사장님만 종류 수정" on public.acm_categories
  for update to authenticated
  using (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())))
  with check (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())));
drop policy if exists "사장님만 종류 삭제" on public.acm_categories;
create policy "사장님만 종류 삭제" on public.acm_categories
  for delete to authenticated
  using (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())));

drop policy if exists "누구나 메뉴 보기" on public.acm_menu_items;
create policy "누구나 메뉴 보기" on public.acm_menu_items
  for select to anon, authenticated using (true);
drop policy if exists "사장님만 메뉴 추가" on public.acm_menu_items;
create policy "사장님만 메뉴 추가" on public.acm_menu_items
  for insert to authenticated
  with check (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())));
drop policy if exists "사장님만 메뉴 수정" on public.acm_menu_items;
create policy "사장님만 메뉴 수정" on public.acm_menu_items
  for update to authenticated
  using (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())))
  with check (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())));
drop policy if exists "사장님만 메뉴 삭제" on public.acm_menu_items;
create policy "사장님만 메뉴 삭제" on public.acm_menu_items
  for delete to authenticated
  using (exists (select 1 from public.acm_owners o where o.user_id = (select auth.uid())));

drop policy if exists "내 사장님 등록만 보기" on public.acm_owners;
create policy "내 사장님 등록만 보기" on public.acm_owners
  for select to authenticated using (user_id = (select auth.uid()));

-- 3) 샘플 메뉴: 표가 비어 있을 때만 넣습니다.
insert into public.acm_categories (name, name_en, sort)
select * from (values ('커피', 'Coffee', 1), ('음료', 'Drinks', 2), ('디저트', 'Dessert', 3)) as v(name, name_en, sort)
where not exists (select 1 from public.acm_categories);

insert into public.acm_menu_items (category_id, name, name_en, price, description, image, sold_out, sort)
select c.id, v.name, v.name_en, v.price, v.description, v.image, v.sold_out, v.sort
from (values
  ('커피', '아메리카노', 'Americano', 4500, '산미가 적은 오늘의 원두로 내립니다.', null, false, 1),
  ('커피', '오후세시 라떼', 'Afternoon Latte', 6000, '고소한 원두에 우유 크림을 얹은 가게 대표 메뉴입니다.', 'images/menu-1.jpg', false, 2),
  ('커피', '오늘의 핸드드립', 'Hand Drip of the Day', 7000, '그날 볶은 원두 중 하나를 골라 천천히 내려 드립니다.', 'images/menu-2.jpg', false, 3),
  ('음료', '유자 에이드', 'Yuja Ade', 6500, '직접 담근 유자청에 탄산수를 섞었습니다.', null, true, 1),
  ('디저트', '무화과 휘낭시에', 'Fig Financier', 3800, '버터 향이 진한 구움과자에 무화과 조림을 넣었습니다.', 'images/menu-3.jpg', false, 1),
  ('디저트', '바스크 치즈케이크', 'Basque Cheesecake', 6000, '겉은 진하게 굽고 속은 부드럽게 남겼습니다.', null, false, 2)
) as v(category, name, name_en, price, description, image, sold_out, sort)
join public.acm_categories c on c.name = v.category
where not exists (select 1 from public.acm_menu_items);
